// <auto-generated />
using DiscordBotApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBotApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250810151825_Initial Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("DiscordBotApi.Data.Channels.DiscordChannel", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildKey")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTextChannel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasAlternateKey("Id");

                    b.HasIndex("GuildKey");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("DiscordBotApi.Data.Guilds.DiscordGuild", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerPrimaryKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasAlternateKey("Id");

                    b.HasIndex("OwnerPrimaryKey");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("DiscordBotApi.Data.Users.DiscordUser", b =>
                {
                    b.Property<int>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiscordGuildKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlobalName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PrimaryKey");

                    b.HasAlternateKey("Id");

                    b.HasAlternateKey("Username");

                    b.HasIndex("DiscordGuildKey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscordBotApi.Data.Channels.DiscordChannel", b =>
                {
                    b.HasOne("DiscordBotApi.Data.Guilds.DiscordGuild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DiscordBotApi.Data.Guilds.DiscordGuild", b =>
                {
                    b.HasOne("DiscordBotApi.Data.Users.DiscordUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerPrimaryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DiscordBotApi.Data.Users.DiscordUser", b =>
                {
                    b.HasOne("DiscordBotApi.Data.Guilds.DiscordGuild", null)
                        .WithMany("Users")
                        .HasForeignKey("DiscordGuildKey");
                });

            modelBuilder.Entity("DiscordBotApi.Data.Guilds.DiscordGuild", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
